version: '3.8'

services:
  ai-service:
    build: ./ai-service
    ports:
      - "8001:8001"
    environment:
      - PYTHONUNBUFFERED=1

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - ai-service

  node-backend:
    build: ./node-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend

  frontend:
    build: ./frontend
    ports:
      - "3001:3000"
    depends_on:
      - node-backend